<?php $this->partial('shared/header'); ?>

<form method="post" class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="page-header">
                <div class="pull-right">
                    <a class="btn btn-default" href="<?= $ref ?>" type="button">Cancel</a>
                    <button class="btn btn-primary">Save</button>
                </div>
                <h3><?= $title ?></h3>
            </div>
        </div>
    </div>
    
    <div class="row">
        <div class="col-md-9">
            <div class="row">
                <div class="col-md-8">
                    <?= $this->form->field('title'); ?>
                </div>
                <div class="col-md-4">
                    <?= $this->form->field('slug'); ?>
                </div>
            </div>
            <?= $this->form->field('content'); ?>
        </div>
        <div class="col-md-3">
            <div class="panel panel-default">
                <div class="panel-body">
                    <?= $this->form->field('meta_schema'); ?>
                    <?= $this->form->field('meta_title'); ?>
                    <?= $this->form->field('meta_description'); ?>
                    <?= $this->form->field('meta_keywords'); ?>
                </div>
            </div>
        </div>
    </div>
</form>

<?php $this->partial('shared/footer'); ?>